"""create_initial_tables

Revision ID: c15179238652
Revises: 
Create Date: 2025-05-25 03:59:56.381059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c15179238652'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('personality_config', sa.JSON(), nullable=True),
    sa.Column('llm_config', sa.JSON(), nullable=True),
    sa.Column('tools_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('event_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scenario_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('agent_roles', sa.JSON(), nullable=True),
    sa.Column('event_flow', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scenario_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['scenario_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('scenario_run_id', sa.Integer(), nullable=True),
    sa.Column('instance_name', sa.String(length=100), nullable=True),
    sa.Column('runtime_config', sa.JSON(), nullable=True),
    sa.Column('state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_run_id'], ['scenario_runs.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['agent_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_run_id', sa.Integer(), nullable=True),
    sa.Column('agent_instance_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_instance_id'], ['agent_instances.id'], ),
    sa.ForeignKeyConstraint(['scenario_run_id'], ['scenario_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_run_id', sa.Integer(), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('source_agent_id', sa.Integer(), nullable=True),
    sa.Column('target_agent_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ),
    sa.ForeignKeyConstraint(['scenario_run_id'], ['scenario_runs.id'], ),
    sa.ForeignKeyConstraint(['source_agent_id'], ['agent_instances.id'], ),
    sa.ForeignKeyConstraint(['target_agent_id'], ['agent_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_instances')
    op.drop_table('execution_logs')
    op.drop_table('agent_instances')
    op.drop_table('scenario_runs')
    op.drop_table('scenario_templates')
    op.drop_table('event_types')
    op.drop_table('agent_templates')
    # ### end Alembic commands ###
